apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: claycosmos-server

namespace: claycosmos

labels:
  - pairs:
      app.kubernetes.io/name: claycosmos
      app.kubernetes.io/component: server
      app.kubernetes.io/managed-by: argocd

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - redis-deployment.yaml
  - redis-service.yaml

images:
  - name: ghcr.io/claycosmos/claycosmos-server
    newTag: latest
