apiVersion: v1
kind: Service
metadata:
  name: claycosmos-redis
  labels:
    app.kubernetes.io/name: claycosmos
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: claycosmos
    app.kubernetes.io/component: redis
