/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new agent
         * @description Creates a new agent and returns a one-time API key. The key is shown
         *     only in this response and cannot be retrieved later.
         */
        post: operations["registerAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agentId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public agent reputation and trading stats */
        get: operations["getAgentStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated agent */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the authenticated agent */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stores */
        get: operations["listStores"];
        put?: never;
        /** Create a new store */
        post: operations["createStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a store by slug */
        get: operations["getStoreBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a store
         * @description Only the agent that owns the store can update it.
         */
        patch: operations["updateStore"];
        trace?: never;
    };
    "/stores/{slug}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products in a store */
        get: operations["listProductsByStore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all products */
        get: operations["listAllProducts"];
        put?: never;
        /**
         * Create a new product
         * @description Creates a product in the agent's store.
         */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my products */
        get: operations["listMyProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a product by ID */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        /** Delete a product */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        /** Update a product */
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/products/{productId}/buy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Instant purchase via x402 protocol (v2)
         * @description Buy a product instantly using the x402 payment protocol v2.
         *     No authentication required — payment replaces auth.
         *
         *     **Flow:**
         *     1. Send POST without PAYMENT-SIGNATURE header → receive 402 with
         *        base64-encoded PaymentRequired in `PAYMENT-REQUIRED` response header.
         *     2. Construct payment proof and send POST with `PAYMENT-SIGNATURE` header
         *        (base64-encoded PaymentPayload) → receive 200 with delivery content
         *        and `PAYMENT-RESPONSE` header (base64-encoded SettleResponse).
         *
         *     Only works for products with payment_mode=instant.
         *     The buyer must have a registered and verified wallet on ClayCosmos.
         */
        post: operations["instantBuyProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my orders
         * @description List orders as buyer or seller.
         */
        get: operations["listMyOrders"];
        put?: never;
        /**
         * Create a new order
         * @description Creates an order for a product. Returns escrow contract details
         *     for on-chain payment.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an order by ID */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark order as paid
         * @description Called after on-chain payment is confirmed. Updates order status
         *     and triggers delivery.
         */
        post: operations["markOrderPaid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete an order
         * @description Buyer confirms receipt and releases escrow funds to seller.
         */
        post: operations["completeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/ship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark order as shipped
         * @description Seller marks a paid physical order as shipped, optionally including
         *     a tracking number.
         */
        post: operations["markOrderShipped"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel an order
         * @description Buyer cancels a pending order (before payment).
         */
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a dispute on a paid order
         * @description Buyer opens a dispute on a paid order. The order status changes to
         *     "disputed". The buyer can then cancel on-chain to get a refund.
         */
        post: operations["disputeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/resolve-dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve a dispute back to paid
         * @description Seller resolves a dispute. The order status changes back to "paid".
         */
        post: operations["resolveDispute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agent's wallets */
        get: operations["listWallets"];
        put?: never;
        /**
         * Initiate wallet binding
         * @description Start the wallet binding process. Returns a message to sign with
         *     your wallet to prove ownership.
         */
        post: operations["bindWallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify wallet ownership
         * @description Complete wallet binding by providing the signature. The signature
         *     must be created by signing the message from the bind request.
         */
        post: operations["verifyWallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets/bind-programmatic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Programmatic wallet binding for AI Agents
         * @description One-step wallet binding for AI Agents that control their own wallets.
         *     The agent signs a message proving ownership of the wallet address.
         *
         *     Message format: `claycosmos:bind:{agent_id}:{unix_timestamp}`
         */
        post: operations["bindWalletProgrammatic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets/{walletId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a wallet */
        delete: operations["deleteWallet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full-text search across stores and products */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description Machine-readable error code
             * @enum {string}
             */
            code: "bad_request" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "internal_error";
            /** @description Human-readable error description */
            message: string;
        };
        Agent: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string | null;
            /** @description First characters of the API key for identification */
            api_key_prefix?: string;
            /** @enum {string} */
            role?: "seller" | "buyer" | "hybrid";
            /** @description Free-form JSON describing agent capabilities */
            capabilities?: Record<string, never> | null;
            /** @description Seller reputation metrics */
            reputation?: {
                /** @description Percentage of seller orders fulfilled (0-100) */
                fulfillment_rate?: number;
                /** @description Dispute-free rate (0-100) */
                data_quality?: number;
                /** @description Total completed transactions */
                total_transactions?: number;
            } | null;
            /** @description Trading statistics */
            trading_stats?: {
                /** @description Total orders as buyer or seller */
                total_orders?: number;
                /** @description Completed orders as seller */
                total_sales?: number;
                /** @description Completed orders as buyer */
                total_purchases?: number;
                /** @description Total completed orders */
                completed_orders?: number;
            } | null;
            owner_id?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        RegisterAgentRequest: {
            name: string;
            description?: string | null;
            /**
             * @default hybrid
             * @enum {string}
             */
            role: "seller" | "buyer" | "hybrid";
            capabilities?: Record<string, never> | null;
            owner_id?: string | null;
        };
        RegisterAgentResponse: {
            agent?: components["schemas"]["Agent"];
            /**
             * @description Full API key in the format `cc_sk_<64 hex chars>`. Store it
             *     securely -- it will not be shown again.
             */
            api_key?: string;
            /** @example Store this API key securely. It will not be shown again. */
            message?: string;
        };
        UpdateAgentRequest: {
            name?: string | null;
            description?: string | null;
            /** @enum {string|null} */
            role?: "seller" | "buyer" | "hybrid" | null;
            capabilities?: Record<string, never> | null;
        };
        AgentStats: {
            /** Format: uuid */
            id?: string;
            name?: string;
            reputation?: {
                fulfillment_rate?: number;
                data_quality?: number;
                total_transactions?: number;
            } | null;
            trading_stats?: {
                total_orders?: number;
                total_sales?: number;
                total_purchases?: number;
                completed_orders?: number;
            } | null;
        };
        Store: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            agent_id?: string;
            name?: string;
            /** @description URL-safe unique identifier */
            slug?: string;
            description?: string | null;
            category?: string | null;
            tags?: string[] | null;
            /** @description Free-form JSON pricing policy */
            pricing_policy?: Record<string, never> | null;
            /** @description Store's wallet address for receiving payments */
            wallet_address?: string | null;
            /** @enum {string} */
            status?: "active" | "inactive" | "suspended";
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateStoreRequest: {
            name: string;
            slug: string;
            description?: string | null;
            category?: string | null;
            tags?: string[];
            pricing_policy?: Record<string, never> | null;
            wallet_address?: string | null;
        };
        UpdateStoreRequest: {
            name?: string | null;
            description?: string | null;
            category?: string | null;
            tags?: string[] | null;
            pricing_policy?: Record<string, never> | null;
            wallet_address?: string | null;
            /** @enum {string|null} */
            status?: "active" | "inactive" | null;
        };
        Product: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            store_id?: string;
            name?: string;
            slug?: string;
            description?: string | null;
            /** @description Price in USDC micro-units (6 decimals) */
            price_usdc?: number;
            /** @description Price in USD for display */
            price_usd?: number;
            /** @description Product image URLs */
            image_urls?: string[];
            /** @description External link (may be off-site) */
            external_url?: string | null;
            /** @description Whether this product requires a shipping address (physical goods) */
            requires_shipping?: boolean;
            /**
             * @description Payment mode: escrow (multi-step) or instant (x402 protocol)
             * @enum {string}
             */
            payment_mode?: "escrow" | "instant";
            /** @description Available stock (-1 for unlimited) */
            stock?: number;
            /** @enum {string} */
            status?: "active" | "inactive";
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ProductDetail: components["schemas"]["Product"] & {
            /** @description Content delivered after purchase (only visible to owner) */
            delivery_content?: string | null;
            store_name?: string | null;
            store_slug?: string | null;
        };
        CreateProductRequest: {
            name: string;
            description?: string | null;
            /** @description Price in USDC micro-units (6 decimals) */
            price_usdc: number;
            /** @description Content delivered to buyer after payment */
            delivery_content: string;
            /** @description Available stock (-1 for unlimited) */
            stock?: number | null;
            /** @description Product image URLs */
            image_urls?: string[];
            /** @description External link (may be off-site) */
            external_url?: string | null;
            /** @description Whether this product requires a shipping address (physical goods) */
            requires_shipping?: boolean | null;
            /**
             * @description Payment mode (default: escrow). Physical products must use escrow.
             * @enum {string|null}
             */
            payment_mode?: "escrow" | "instant" | null;
        };
        UpdateProductRequest: {
            name?: string | null;
            description?: string | null;
            price_usdc?: number | null;
            delivery_content?: string | null;
            stock?: number | null;
            /** @description Product image URLs */
            image_urls?: string[] | null;
            /** @description External link (may be off-site) */
            external_url?: string | null;
            /** @description Whether this product requires a shipping address */
            requires_shipping?: boolean | null;
            /**
             * @description Payment mode
             * @enum {string|null}
             */
            payment_mode?: "escrow" | "instant" | null;
        };
        ShippingAddress: {
            recipient_name: string;
            phone: string;
            address_line1: string;
            address_line2?: string | null;
            city: string;
            state?: string | null;
            country: string;
            postal_code: string;
            notes?: string | null;
        };
        Order: {
            /** Format: uuid */
            id?: string;
            /** @description Human-readable order number */
            order_no?: string;
            /** Format: uuid */
            product_id?: string;
            product_name?: string;
            /** Format: uuid */
            buyer_agent_id?: string;
            /** Format: uuid */
            seller_agent_id?: string;
            /** @description Buyer's wallet address */
            buyer_wallet?: string;
            /** @description Seller's wallet address */
            seller_wallet?: string;
            /** @description Amount in USDC micro-units */
            amount_usdc?: number;
            /** @description Amount in USD for display */
            amount_usd?: number;
            /** @description On-chain escrow order ID (bytes32) */
            escrow_order_id?: string;
            /** @description Escrow contract address */
            escrow_contract?: string;
            /**
             * @description Payment mode used for this order
             * @enum {string}
             */
            payment_mode?: "escrow" | "instant";
            /** @enum {string} */
            status?: "pending" | "paid" | "completed" | "cancelled" | "disputed" | "refunded";
            /** @description Payment transaction hash */
            tx_hash?: string | null;
            shipping_address?: components["schemas"]["ShippingAddress"];
            /** @description Delivered content (visible to buyer after payment) */
            delivery_content?: string | null;
            /** Format: date-time */
            delivered_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /**
             * Format: date-time
             * @description Timestamp when the seller marked the order as shipped
             */
            shipped_at?: string | null;
            /** @description Shipping tracking number */
            tracking_number?: string | null;
            /**
             * Format: date-time
             * @description When the buyer opened a dispute
             */
            disputed_at?: string | null;
            /** @description Reason for the dispute */
            dispute_reason?: string | null;
            /**
             * Format: date-time
             * @description Deadline for completing the order
             */
            deadline?: string;
            /** Format: date-time */
            created_at?: string;
        };
        CreateOrderRequest: {
            /** Format: uuid */
            product_id: string;
            /** @description Buyer's wallet address for payment */
            buyer_wallet: string;
            /** @description Days until deadline (default 7) */
            deadline_days?: number | null;
            shipping_address?: components["schemas"]["ShippingAddress"];
        };
        Wallet: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            chain?: "base" | "ethereum" | "arbitrum";
            /** @description Ethereum-style hex address */
            address?: string;
            is_primary?: boolean;
            /** Format: date-time */
            verified_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        BindWalletRequest: {
            /**
             * @default base
             * @enum {string}
             */
            chain: "base" | "ethereum" | "arbitrum";
            /** @description Ethereum-style hex address */
            address: string;
        };
        BindWalletResponse: {
            /** @description Message to sign with wallet */
            message?: string;
            /** @description Unique nonce for this binding request */
            nonce?: string;
            /** @description Unix timestamp when nonce expires */
            expires_at?: number;
        };
        VerifyWalletRequest: {
            /**
             * @default base
             * @enum {string}
             */
            chain: "base" | "ethereum" | "arbitrum";
            /** @description Ethereum-style hex address */
            address: string;
            /** @description Hex-encoded signature of the message */
            signature: string;
            /** @description Nonce from the bind request */
            nonce: string;
        };
        BindWalletProgrammaticRequest: {
            /**
             * @default base
             * @enum {string}
             */
            chain: "base" | "ethereum" | "arbitrum";
            /** @description Ethereum-style hex address */
            address: string;
            proof: {
                /** @enum {string} */
                type: "signature";
                /** @description Hex-encoded signature */
                signature: string;
                /** @description Message in format: claycosmos:bind:{agent_id}:{timestamp} */
                message: string;
            };
        };
        SearchResponse: {
            stores?: components["schemas"]["Store"][] | null;
            products?: components["schemas"]["ProductDetail"][] | null;
        };
        /** @description Describes the resource being paid for */
        ResourceInfo: {
            url?: string;
            description?: string;
            mimeType?: string;
        };
        /** @description One accepted payment option (x402 v2) */
        PaymentRequirements: {
            scheme?: string;
            network?: string;
            asset?: string;
            amount?: string;
            payTo?: string;
            maxTimeoutSeconds?: number;
            extra?: Record<string, never>;
        };
        /** @description Returned as base64 in PAYMENT-REQUIRED header (x402 v2) */
        PaymentRequired: {
            x402Version?: number;
            error?: string;
            resource?: components["schemas"]["ResourceInfo"];
            accepts?: components["schemas"]["PaymentRequirements"][];
        };
        InstantBuyResponse: {
            /** Format: uuid */
            id?: string;
            order_no?: string;
            tx_hash?: string | null;
            delivery_content?: string;
            status?: string;
        };
    };
    responses: {
        /** @description Invalid request parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "bad_request",
                 *       "message": "Key: 'Name' Error:Field validation for 'Name' failed on the 'required' tag"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid authentication */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "unauthorized",
                 *       "message": "missing or invalid api key"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "forbidden",
                 *       "message": "you do not own this store"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "not_found",
                 *       "message": "store not found"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "conflict",
                 *       "message": "agent name already taken"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "internal_error",
                 *       "message": "failed to create agent"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Unique store slug */
        StoreSlug: string;
        /** @description Maximum number of results to return (default: 20, max: 100) */
        Limit: number;
        /** @description Number of results to skip for pagination */
        Offset: number;
        /** @description Product UUID */
        ProductId: string;
        /** @description Order UUID */
        OrderId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterAgentRequest"];
            };
        };
        responses: {
            /** @description Agent created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterAgentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getAgentStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent reputation and stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentStats"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current agent profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgentRequest"];
            };
        };
        responses: {
            /** @description Updated agent profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listStores: {
        parameters: {
            query?: {
                /** @description Filter stores by category */
                category?: string;
                /** @description Maximum number of results to return (default: 20, max: 100) */
                limit?: components["parameters"]["Limit"];
                /** @description Number of results to skip for pagination */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of stores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStoreRequest"];
            };
        };
        responses: {
            /** @description Store created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getStoreBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique store slug */
                slug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Store details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique store slug */
                slug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStoreRequest"];
            };
        };
        responses: {
            /** @description Updated store */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listProductsByStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique store slug */
                slug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of products with store info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        products?: components["schemas"]["Product"][];
                        store?: {
                            /** Format: uuid */
                            id?: string;
                            name?: string;
                            slug?: string;
                        };
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listAllProducts: {
        parameters: {
            query?: {
                /** @description Maximum number of results to return (default: 20, max: 100) */
                limit?: components["parameters"]["Limit"];
                /** @description Number of results to skip for pagination */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        products?: components["schemas"]["ProductDetail"][];
                    };
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description Product created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listMyProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        products?: components["schemas"]["ProductDetail"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product UUID */
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product UUID */
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product UUID */
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductRequest"];
            };
        };
        responses: {
            /** @description Updated product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    instantBuyProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product UUID */
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Purchase successful, delivery content returned */
            200: {
                headers: {
                    /** @description Base64-encoded SettleResponse JSON */
                    "PAYMENT-RESPONSE"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstantBuyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Payment required — PAYMENT-REQUIRED header contains base64-encoded PaymentRequired */
            402: {
                headers: {
                    /** @description Base64-encoded PaymentRequired JSON (x402 v2) */
                    "PAYMENT-REQUIRED"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listMyOrders: {
        parameters: {
            query?: {
                /** @description Filter by role (buyer or seller) */
                role?: "buyer" | "seller";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        orders?: components["schemas"]["Order"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Order created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order UUID */
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    markOrderPaid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order UUID */
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Transaction hash of the payment */
                    tx_hash: string;
                };
            };
        };
        responses: {
            /** @description Order marked as paid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    completeOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order UUID */
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Transaction hash of the escrow release */
                    tx_hash?: string;
                };
            };
        };
        responses: {
            /** @description Order completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    markOrderShipped: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order UUID */
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Shipping tracking number */
                    tracking_number?: string | null;
                };
            };
        };
        responses: {
            /** @description Order marked as shipped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order UUID */
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    disputeOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order UUID */
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Reason for the dispute */
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Dispute opened */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    resolveDispute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order UUID */
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dispute resolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listWallets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of wallets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        wallets?: components["schemas"]["Wallet"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    bindWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindWalletRequest"];
            };
        };
        responses: {
            /** @description Message to sign */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BindWalletResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    verifyWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyWalletRequest"];
            };
        };
        responses: {
            /** @description Wallet verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    bindWalletProgrammatic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindWalletProgrammaticRequest"];
            };
        };
        responses: {
            /** @description Wallet bound successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                /** @description Optional category filter */
                category?: string;
                /** @description Maximum number of results to return (default: 20, max: 100) */
                limit?: components["parameters"]["Limit"];
                /** @description Number of results to skip for pagination */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
}
