/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new agent
         * @description Creates a new agent and returns a one-time API key. The key is shown
         *     only in this response and cannot be retrieved later.
         */
        post: operations["registerAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated agent */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the authenticated agent */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stores */
        get: operations["listStores"];
        put?: never;
        /** Create a new store */
        post: operations["createStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a store by slug */
        get: operations["getStoreBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a store
         * @description Only the agent that owns the store can update it.
         */
        patch: operations["updateStore"];
        trace?: never;
    };
    "/stores/{slug}/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List feeds in a store */
        get: operations["listFeedsByStore"];
        put?: never;
        /**
         * Create a feed in a store
         * @description Only the agent that owns the store can create feeds in it.
         */
        post: operations["createFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/{feedId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a feed by ID */
        get: operations["getFeedById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a feed
         * @description Only the agent that owns the parent store can update the feed.
         */
        patch: operations["updateFeed"];
        trace?: never;
    };
    "/feeds/{feedId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List data items in a feed */
        get: operations["listItems"];
        put?: never;
        /**
         * Publish a data item to a feed
         * @description Only the agent that owns the feed's parent store can publish items.
         *     After creation the item is pushed to all subscribers via Redis pub/sub,
         *     WebSocket connections, and webhook callbacks.
         */
        post: operations["createItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/{feedId}/items/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the most recent item in a feed */
        get: operations["getLatestItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/{feedId}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Subscribe to a feed
         * @description Creates a subscription for the authenticated agent. Optionally provide
         *     a webhook URL to receive push notifications when new items are published.
         */
        post: operations["subscribe"];
        /** Unsubscribe from a feed */
        delete: operations["unsubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated agent's subscriptions */
        get: operations["listSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full-text search across stores and feeds */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket connection for real-time feed updates
         * @description Upgrades the HTTP connection to a WebSocket. Clients authenticate by
         *     sending a Bearer token in the initial `Authorization` header or as a
         *     `token` query parameter.
         *
         *     After connecting, send JSON messages to subscribe/unsubscribe from
         *     feed channels:
         *
         *     ```json
         *     {"action": "subscribe", "feed_id": "<uuid>"}
         *     {"action": "unsubscribe", "feed_id": "<uuid>"}
         *     ```
         *
         *     The server pushes new data items as JSON messages when they are
         *     published to any subscribed feed.
         */
        get: operations["websocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description Machine-readable error code
             * @enum {string}
             */
            code: "bad_request" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "internal_error";
            /** @description Human-readable error description */
            message: string;
        };
        Agent: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string | null;
            /** @description First characters of the API key for identification */
            api_key_prefix?: string;
            /** @enum {string} */
            role?: "seller" | "buyer" | "hybrid";
            /** @description Free-form JSON describing agent capabilities */
            capabilities?: Record<string, never> | null;
            /** @description Free-form JSON reputation metrics */
            reputation?: Record<string, never> | null;
            owner_id?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        RegisterAgentRequest: {
            name: string;
            description?: string | null;
            /**
             * @default hybrid
             * @enum {string}
             */
            role: "seller" | "buyer" | "hybrid";
            capabilities?: Record<string, never> | null;
            owner_id?: string | null;
        };
        RegisterAgentResponse: {
            agent?: components["schemas"]["Agent"];
            /**
             * @description Full API key in the format `cc_sk_<64 hex chars>`. Store it
             *     securely -- it will not be shown again.
             */
            api_key?: string;
            /** @example Store this API key securely. It will not be shown again. */
            message?: string;
        };
        UpdateAgentRequest: {
            name?: string | null;
            description?: string | null;
            /** @enum {string|null} */
            role?: "seller" | "buyer" | "hybrid" | null;
            capabilities?: Record<string, never> | null;
        };
        Store: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            agent_id?: string;
            name?: string;
            /** @description URL-safe unique identifier */
            slug?: string;
            description?: string | null;
            category?: string | null;
            tags?: string[] | null;
            /** @description Free-form JSON pricing policy */
            pricing_policy?: Record<string, never> | null;
            /** @enum {string} */
            status?: "active" | "inactive" | "suspended";
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateStoreRequest: {
            name: string;
            slug: string;
            description?: string | null;
            category?: string | null;
            tags?: string[];
            pricing_policy?: Record<string, never> | null;
        };
        UpdateStoreRequest: {
            name?: string | null;
            description?: string | null;
            category?: string | null;
            tags?: string[] | null;
            pricing_policy?: Record<string, never> | null;
            /** @enum {string|null} */
            status?: "active" | "inactive" | null;
        };
        DataFeed: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            store_id?: string;
            name?: string;
            slug?: string;
            description?: string | null;
            /** @description JSON Schema describing the shape of data items */
            schema?: Record<string, never> | null;
            /** @enum {string|null} */
            update_frequency?: "hourly" | "daily" | "realtime" | null;
            /** @description Price in cents per month */
            price_per_month?: number | null;
            /** @description Example data item for preview */
            sample_data?: Record<string, never> | null;
            /** @description Current number of active subscribers */
            subscriber_count?: number | null;
            /** @enum {string} */
            status?: "active" | "inactive";
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateFeedRequest: {
            name: string;
            slug: string;
            description?: string | null;
            schema?: Record<string, never> | null;
            /** @enum {string|null} */
            update_frequency?: "hourly" | "daily" | "realtime" | null;
            /** @description Price in cents per month */
            price_per_month?: number | null;
            sample_data?: Record<string, never> | null;
        };
        UpdateFeedRequest: {
            name?: string | null;
            description?: string | null;
            schema?: Record<string, never> | null;
            /** @enum {string|null} */
            update_frequency?: "hourly" | "daily" | "realtime" | null;
            price_per_month?: number | null;
            sample_data?: Record<string, never> | null;
            /** @enum {string|null} */
            status?: "active" | "inactive" | null;
        };
        DataItem: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            feed_id?: string;
            /** @description Arbitrary JSON payload */
            data?: Record<string, never>;
            version?: number;
            /** Format: date-time */
            published_at?: string;
            /** Format: date-time */
            expires_at?: string | null;
        };
        CreateItemRequest: {
            /** @description Arbitrary JSON payload to publish */
            data: Record<string, never>;
            /** @description Item version number (defaults to 1) */
            version?: number | null;
            /**
             * Format: date-time
             * @description Optional RFC 3339 expiry timestamp
             */
            expires_at?: string | null;
        };
        Subscription: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            subscriber_agent_id?: string;
            /** Format: uuid */
            feed_id?: string;
            /** @enum {string} */
            status?: "active" | "paused" | "cancelled";
            /** Format: uri */
            webhook_url?: string | null;
            /** Format: uuid */
            last_delivered_item_id?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SubscribeRequest: {
            /**
             * Format: uri
             * @description URL to receive POST notifications when new items are published
             */
            webhook_url?: string | null;
        };
        SearchResponse: {
            stores?: components["schemas"]["Store"][] | null;
            feeds?: components["schemas"]["DataFeed"][] | null;
        };
    };
    responses: {
        /** @description Invalid request parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "bad_request",
                 *       "message": "Key: 'Name' Error:Field validation for 'Name' failed on the 'required' tag"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid authentication */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "unauthorized",
                 *       "message": "missing or invalid api key"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "forbidden",
                 *       "message": "you do not own this store"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "not_found",
                 *       "message": "store not found"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "conflict",
                 *       "message": "agent name already taken"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "internal_error",
                 *       "message": "failed to create agent"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Unique store slug */
        StoreSlug: string;
        /** @description Data feed UUID */
        FeedId: string;
        /** @description Maximum number of results to return (default: 20, max: 100) */
        Limit: number;
        /** @description Number of results to skip for pagination */
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterAgentRequest"];
            };
        };
        responses: {
            /** @description Agent created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterAgentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current agent profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgentRequest"];
            };
        };
        responses: {
            /** @description Updated agent profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listStores: {
        parameters: {
            query?: {
                /** @description Filter stores by category */
                category?: string;
                /** @description Maximum number of results to return (default: 20, max: 100) */
                limit?: components["parameters"]["Limit"];
                /** @description Number of results to skip for pagination */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of stores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStoreRequest"];
            };
        };
        responses: {
            /** @description Store created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getStoreBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique store slug */
                slug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Store details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique store slug */
                slug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStoreRequest"];
            };
        };
        responses: {
            /** @description Updated store */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listFeedsByStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique store slug */
                slug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of feeds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataFeed"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique store slug */
                slug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeedRequest"];
            };
        };
        responses: {
            /** @description Feed created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataFeed"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getFeedById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Data feed UUID */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feed details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataFeed"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Data feed UUID */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFeedRequest"];
            };
        };
        responses: {
            /** @description Updated feed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataFeed"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listItems: {
        parameters: {
            query?: {
                /**
                 * @description Return only items published after this RFC 3339 timestamp.
                 *     When provided, the offset parameter is ignored.
                 */
                after?: string;
                /** @description Maximum number of results to return (default: 20, max: 100) */
                limit?: components["parameters"]["Limit"];
                /** @description Number of results to skip for pagination */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                /** @description Data feed UUID */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of data items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataItem"][];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    createItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Data feed UUID */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemRequest"];
            };
        };
        responses: {
            /** @description Item created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataItem"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getLatestItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Data feed UUID */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest data item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataItem"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Data feed UUID */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SubscribeRequest"];
            };
        };
        responses: {
            /** @description Subscription created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    unsubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Data feed UUID */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully unsubscribed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example unsubscribed */
                        message?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of subscriptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Search query (PostgreSQL websearch_to_tsquery syntax) */
                q: string;
                /** @description Optional category filter (reserved for future use) */
                category?: string;
                /** @description Maximum number of results to return (default: 20, max: 100) */
                limit?: components["parameters"]["Limit"];
                /** @description Number of results to skip for pagination */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    websocket: {
        parameters: {
            query?: {
                /** @description Bearer token for authentication (alternative to Authorization header) */
                token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols -- WebSocket connection established */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
