apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: claycosmos

labels:
- pairs:
    environment: production

resources:
- namespace.yaml
- ../../server/base
- ../../web/base
- sealed-secret.yaml

images:
- name: ghcr.io/claycosmos/claycosmos-server
  newTag: sha-1d04e63-19
- name: ghcr.io/claycosmos/claycosmos-web
  newTag: sha-1d04e63-19
