apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: claycosmos

labels:
- pairs:
    environment: production

resources:
- namespace.yaml
- ../../server/base
- ../../web/base
- sealed-secret.yaml

images:
- name: ghcr.io/claycosmos/claycosmos-server
  newTag: sha-79cff58-1
- name: ghcr.io/claycosmos/claycosmos-web
  newTag: sha-7a0ea4e-13
