apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: claycosmos

labels:
- pairs:
    environment: production

resources:
- ../../base

images:
- name: ghcr.io/ClayCosmos/claycosmos-web
  newTag: sha-b746c02-5
- name: ghcr.io/claycosmos/claycosmos-web
  newTag: latest
